project/project/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('', include('simpleapp.urls')),
    path('', include('protect.urls')),
    path('sign/', include('sign.urls')),
    path('accounts/', include('allauth.urls')),
]

project/sign/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import BaseRegisterView, upgrade_me

urlpatterns = [
    path('login/',
         LoginView.as_view(template_name = 'sign/login.html'),
         name='login'),
    path('logout/',
         LogoutView.as_view(template_name = 'sign/logout.html'),
         name='logout'),
    path('signup/',
         BaseRegisterView.as_view(template_name = 'sign/signup.html'),
         name='signup'),
    path('upgrade/', upgrade_me, name = 'upgrade')

]

project/simpleapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator
from django.urls import reverse

NEWS_OR_ARTICLE = [
    ('article', 'Статья'),
    ('news', 'Новость'),
]


class Author(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    author_rating = models.IntegerField(default=0)

    def update_rating(self):
        self.author_rating = 0
        post,comment = 1, 1

        for post in Post.objects.filter(author=self):
            self.author_rating += post.post_rating*3

        for comment in Comment.objects.filter(user=self):
            self.author_rating += comment.comment_rating

        for comment in Comment.objects.filter(post__author=self):
            self.author_rating += comment.comment_rating
        Author.objects.filter(id=self.id).update(author_rating=self.author_rating)


class Post(models.Model):
    id = models.AutoField(primary_key=True)
    title_of_post = models.CharField(max_length=100)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    post_text = models.TextField()
    news_or_article = models.CharField(max_length=8, choices=NEWS_OR_ARTICLE, default='article')
    post_rating = models.IntegerField(default=0)
    date_of_post = models.DateTimeField(auto_now_add=True)
    category = models.ManyToManyField('category', through='PostCategory')

    def like(self):
        self.post_rating += 1
        self.save()

    def dislike(self):
        self.post_rating -= 1
        self.save()

    def preview(self):
        return f'{self.post_text[:20 if len(self.post_text) > 20 else self.post_text]}'

    def get_absolute_url(self):
        return reverse('post_detail', args=[str(self.id)])

    #def __str__(self):
    #    return f'{self.title_of_post}: {self.date_of_post}: {self.post_text[:20 if len(self.post_text) > 20 else self.post_text]}'


class Comment(models.Model):
    id = models.AutoField(primary_key=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(Author, on_delete=models.CASCADE)
    comment_text = models.TextField()
    date_of_comment = models.DateTimeField(auto_now_add=True)
    comment_rating = models.IntegerField(default=0)

    def like(self):
        self.comment_rating += 1
        self.save()

    def dislike(self):
        self.comment_rating -= 1
        self.save()


class Category(models.Model):
    name = models.CharField(primary_key=True, max_length=100)

    def __str__(self):
        return self.name


class PostCategory(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)


class Subscribers(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.category}: {self.user}'

project/templates/Subscribe.html
<html lang="en">
<head>
    <meta charset="UTF-8">
</head>
<body>
    <h1>Подписка на категории</h1>
    <form method="post" action="{% url 'subscribe' %}" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Подписаться</button>
    </form>
<h3>{{ message }}</h3>
{% if not request.session.is_subscribed %}
<h3>{{ request.session.subscriber_category }}</h3>
{% endif %}
</body>
</html>

project/templates/category.html

<html lang="en">
<head>
    <meta charset="UTF-8">
</head>
<body>
    <h1>Подписка на категории</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        {% for categor in category %}
        <br><td>{{ categor }}</td></br>
        <br><td>Количество постов в данной категории: {{ categor.post_set.count }}</td></br>
        <button> <a href="category/1/subscribe"> Подписаться!</a> </button>
        {% endfor %}
    </form>
</body>
</html>

project/templates/main.html
<html>
    <head>
        <title> Simple SignUp/SignIn app</title>
    </head>
    <body>
        <div>
            <h1><a href="/">Simple SignUp/SignIn app</a></h1>        </div>
        {% block content %}
        {% endblock %}
    </body>
</html>

project/templates/post.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}

<!-- Название у нас будет products -->
{% block title %}
Posts
{% endblock title %}

<!-- В контенте на странице мы выводим все товары -->
{% block content %}
   <h1>Подробности поста</h1>
   <!-- Используем переданную из представления переменную time_now
   и применяем к ней фильтр date. По назначению этот фильтр очень похож
   на метод strftime у объекта datetime в Python — вывод времени
   в указанном формате. -->
   <h3>{{ time_now|date:'M d Y' }}</h3>
   <hr>
       <table>
           <tr>
               <td><h2>Название</h2></td>
               <td><h2>Дата публикации</h2></td>
               <td><h2>Полный текст</h2></td>
           </tr>
           <tr>
               <td>{{ post.title_of_post|censor }}</td>
               <td>{{ post.date_of_post|date:'d M Y' }}</td>
               <!--<td>{{ post.post_text|censor }}</td>-->
               <td>{{ post.post_text|censor }}</td>
           </tr>

       </table>

{% endblock content %}

project/templates/post_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление поста</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем "{{ object.title_of_post }}"?</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

project/templates/post_edit.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Посты</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

project/templates/posts.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}
{# Импортируем модуль с нашим тегом #}
{% load custom_tags %}
<!-- Название у нас будет products -->
{% block title %}
Posts
{% endblock title %}

<!-- В контенте на странице мы выводим все товары -->
{% block content %}
   <h1>Все посты</h1>
   <button> <a href="create/"> Опубликовать новость!</a> </button>
   <form action="" method="get">
       {{ filterset.form.as_p }}
       <label for="start">Начальная дата:</label>
       <input type="date" id="start" name="date_of_post__gt" value="2023-10-14" min="2018-01-01" max="2028-12-31" />
       <input type="submit" value="Найти" />

   </form>

   <!-- Используем переданную из представления переменную time_now
   и применяем к ней фильтр date. По назначению этот фильтр очень похож
   на метод strftime у объекта datetime в Python — вывод времени
   в указанном формате. -->
   <h3>{{ time_now|date:'M d Y' }}</h3>
   <hr>
   {% if posts %}
       <table>
           <tr>
               <td><h2>Название</h2></td>
               <td><h2>Дата публикации</h2></td>
               <td><h2>Предпросмотр текста</h2></td>
           </tr>

           {% for post in posts %}
           <tr>
               <td>{{ post.title_of_post|censor }}</td>
               <td>{{ post.date_of_post}}</td>
               <!--<td>{{ post.post_text|censor }}</td>-->
               <td>{{ post.preview|censor }}</td>
           </tr>
           {% endfor %}

       </table>
   {% else %}
        {{ posts }}
       <h2>Постов нет!</h2>
   {% endif %}

   {% if page_obj.has_previous %}
       {# Для каждой ссылки пагинации указываем обработку через новый тег #}
       <a href="?{% url_replace page=1 %}">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {{ page_obj.number }}

   {% if page_obj.has_next %}
       <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

{% endblock content %}